### ISSUE TITLE
ci: Setup windows builds

### ISSUE THREAD

**Issue by ieei** [ieei/rlib#22]
Using appveyor.com is one viable alternative

**Comment by ieei** [comment]
inspired from https://github.com/Microsoft/bond/blob/master/appveyor.yml

this might work with some fixes??
```
-
    version: 1.0.{build}
    clone_depth: 15
    environment:
        matrix:
          - VARIANT: debug
          - VARIANT: release
    build_script:
        - ps: >-
           python waf configure
           python waf --variant=${env:VARIANT} build test
    test_script:
        - ps: >-
           _build_\${env:VARIANT}\test\rlibtest
```
